apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookiebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookiebot
  template:
    metadata:
      labels:
        app: cookiebot
    spec:
      containers:
      - name: cookiebot
        image: cookiebot:latest
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TZ
          value: "UTC"
        volumeMounts:
        - name: secrets
          mountPath: /app/.env
          subPath: .env
        - name: secrets
          mountPath: /app/cookiebot-bucket-key.json
          subPath: cookiebot-bucket-key.json
        - name: secrets
          mountPath: /app/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: secrets
        secret:
          secretName: cookiebot-secrets