import re
URL_REGEX = r'\b((?:https?|ftp|file):\/\/[-a-zA-Z0-9+&@#\/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#\/%=~_|])'
MY_STRING = 'MAS QUE BAITA NOTÍCIA, TCHÊ! 😱 FurSMeetinho 2023 chegou e vai estar cheio de revelações!! 🤯 \n5 HORAS DE MUITA DIVERSÃO GARANTIDA 🎉\n\n🎟️Valor do ingresso: R$25\n🎟️🎳Valor do ingresso + boliche pós evento: R$40\n👉 Compre aqui 👉 https://forms.gle/YrU1TxKaUmi3FUhv9\n\nNesse evento teremos a REVELAÇÃO AO VIVO DA DATA DO FurSMeet 2023 E VENDA DOS SEUS INGRESSOS!!! Os ingressos comprados pela gurizada no FurSMeetinho terão uma surpresa 😱 NÃO ACABA AI!!! Vamos ter 2 atividades surpresas pros piá do evento, conseguem adivinhar oq é?? 🎤📹\nVocês estão prontos pra tantas revelações??\n\nSe você leu até aqui,vou te dar de presente um SPOILERZÃO:\n⚠️ESSE FURSMEETINHO SERÁ REALIZADO NO HOTEL DO FURSMEET 2023⚠️\n\nDúvidas?? Mande uma mensagem para nós!\nTem interesse em ser Estande no FurSMeetinho 2023? Entre em contato conosco nas nossas redes sociais ou com @prisma_arco_iris no telegram ❤️\nNão conhece ninguém que vá?? Da uma bizoiada no nosso chat do telegram pra fazer amizades e não ficar perdido! 👉  http://t.me/fursmeetchat/'
MY_STRING_2 = "﹥*:ꔫ:*+ F2U tiny critter base +*:ꔫ:*﹤\n\nplease credit puppyv0m1t upon use\n\nhttps://toyhou.se/31333661.tiny-critter-base-f2u\n\n︶꒦꒷♡꒷꒦︶\n\nBoundaries:\n\n︶꒦꒷♡꒷꒦︶\n\nDO:\n\ncredit me always\n\nedit it in any way you wish\n\ngift edits to friends\n\nfrankenstein it\n\nmake and sell designs\n\n\n\nDON'T:\n\nclaim it as you own\n\nresell the original or minimally edited lines\n\nsell editing commissions\n\n‧̍ · ‧̥°̩̥˚̩̩̥͙°̩̥‧̥· ‧̍  ♡ °̩̥˚̩̩̥͙°̩̥ ·͙*̩̩͙˚̩̥̩̥*̩̩̥͙·̩̩̥͙*̩̩̥͙˚̩̥̩̥*̩̩͙‧͙ °̩̥˚̩̩̥͙°̩̥ ♡ ‧̍ · ‧̥°̩̥˚̩̩̥͙°̩̥‧̥· ‧̍ \n\n\n\n-ˏˋ Have fun !! If you use the base pls show me ! Id love to see your work  ˊˎ'"
urls = re.findall(URL_REGEX, MY_STRING_2)

for url in urls:
    name = url.rstrip('/').split('/')[-1].replace('www.', '')
    print(name, url)
